ALTER TABLE FB.torrent MODIFY COLUMN releaser VARCHAR(255)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE FB.torrent MODIFY COLUMN torr_name VARCHAR(255)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE FB.torrent MODIFY COLUMN category VARCHAR(255)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
